name: Build Resume
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t resume .
    - name: Run build
      run: docker run --rm -v ${{ github.workspace }}:/src resume
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: Resume
        path: cv/resume.pdf
