name: Build Resume
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: blang/latex:ubuntu
    steps:
    - uses: actions/checkout@v4
    - name: Build PDF
      run: |
        cd src
        pdflatex resume.tex
        mv resume.pdf ../
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: resume.pdf