name: Build Resume
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup LaTeX
      uses: xu-cheng/setup-texlive@v3
    - name: Compile
      run: |
        mkdir -p out
        pdflatex -output-directory=./out src/resume.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: out/resume.pdf